version: '1.0.0'

services:
  postgres:
    container_name: postgres_db
    image: postgres:14.20
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    container_name: pg_admin
    image: elestio/pgadmin:REL-9_8
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - 8080:8080
    restart: always
